name: Run tests
on: [push, pull_request]

jobs:
  unit-test:
    name: Unit test${{ matrix.coverage && ' (with coverage)' || '' }}${{ matrix.random && ' (in random order)' || '' }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. This avoids running the workflows twice in such a case.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6']
        coverage: [false]
        random: [false]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, iconv, json, libxml, zip
          coverage: ${{ matrix.coverage && 'pcov' || 'none' }}
          ini-values: pcov.directory=.
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer install
          cat /etc/php/5.6/cli/php.ini

      - name: Run tests
        if: ${{ matrix.random == false && matrix.coverage == false }}
        run: composer unit
